version: "3.9"
services:
  app:
    build: .
    container_name: analyse-montres
    ports:
      - "8701:8701"
    environment:
      - CHEMIN_BDD=/app/data/propre.xlsx
    volumes:
      - ./data:/app/data:ro
      - ./app:/app/app:ro
      - ./main.py:/app/main.py:ro
  nginx:
    image: nginx:latest
    container_name: analyse-montres-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./_nginx_/conf.d:/etc/nginx/conf.d:ro